const jenisSampahAnorganik = [
  "Plastik",
  "Kertas",
  "Kaleng",
  "Kaca",
  "Besi",
  "Kain",
  "Aluminium",
  "Seng",
  "Tembaga",
  "Botol bekas",
  "Kardus bekas",
  "Gelas pecah",
  "Keramik",
  "Lembaran baja",
  "Baterai bekas",
  "Aki bekas",
  "Pipa PVC",
  "Kawat",
  "Tutup botol",
  "Tutup kaleng",
  "Tutup botol plastik",
  "Lampu pijar",
  "Lampu neon",
  "Lampu LED",
  "CD bekas",
  "Keyboard bekas",
  "Mouse bekas",
  "Hard disk bekas",
  "Monitor bekas",
  "Televisi bekas",
  "Kulkas bekas",
  "AC bekas",
  "Peralatan elektronik bekas",
  "Rokok bekas",
  "Tisu bekas",
  "Sikat gigi bekas",
  "Tongkat pemukul bola golf",
  "Mainan plastik bekas",
];

export default jenisSampahAnorganik;
